<template><div><h2 id="一、background" tabindex="-1"><a class="header-anchor" href="#一、background" aria-hidden="true">#</a> 一、Background</h2>
<p>After running the springboot project, when using postman to test the interface, the console of idea has the following prompt:</p>
<div class="language-java ext-java line-numbers-mode"><pre v-pre class="language-java"><code><span class="token class-name">Initializing</span> <span class="token class-name">Spring</span> <span class="token class-name">DispatcherServlet</span> 'dispatcherServlet'
<span class="token class-name">Initializing</span> <span class="token class-name">Servlet</span> 'dispatcherServlet'
<span class="token class-name">Completed</span> initialization in <span class="token number">1</span> ms
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="二、cause-analysis" tabindex="-1"><a class="header-anchor" href="#二、cause-analysis" aria-hidden="true">#</a> 二、Cause Analysis</h2>
<p>The default value of spring boot load on startup is -1. When the project is started, the dispatcherservlet will not be initialized by default, that is, the init () method of the servlet interface will not be called.</p>
<h2 id="三、resolvent" tabindex="-1"><a class="header-anchor" href="#三、resolvent" aria-hidden="true">#</a> 三、Resolvent</h2>
<p>Set <strong>spring.mvc.servlet.load-on-startup</strong> to <strong>0 or a positive integer</strong>, and execute initialization when the project starts.</p>
<h3 id="method1、add-the-following-configuration-in-the-application-properties-configuration-file" tabindex="-1"><a class="header-anchor" href="#method1、add-the-following-configuration-in-the-application-properties-configuration-file" aria-hidden="true">#</a> Method1、Add the following configuration in the application.properties configuration file</h3>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>spring.mvc.servlet.load-on-startup=1
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="method2、add-the-following-configuration-in-the-application-yml-configuration-file" tabindex="-1"><a class="header-anchor" href="#method2、add-the-following-configuration-in-the-application-yml-configuration-file" aria-hidden="true">#</a> Method2、Add the following configuration in the application.yml configuration file</h3>
<div class="language-yaml ext-yml line-numbers-mode"><pre v-pre class="language-yaml"><code><span class="token key atrule">spring</span><span class="token punctuation">:</span>
  <span class="token key atrule">mvc</span><span class="token punctuation">:</span>
    <span class="token key atrule">servlet</span><span class="token punctuation">:</span>
      <span class="token key atrule">load-on-startup</span><span class="token punctuation">:</span> <span class="token number">1</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>Methods 1 and 2 are equivalent to adding the following configuration in the web.xml file of the spring MVC project:</p>
<div class="language-xml ext-xml line-numbers-mode"><pre v-pre class="language-xml"><code>  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>servlet</span><span class="token punctuation">></span></span>
  	<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>servlet-name</span><span class="token punctuation">></span></span>dispatcher<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>servlet-name</span><span class="token punctuation">></span></span>
  	<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>servlet-class</span><span class="token punctuation">></span></span>org.springframework.web.servlet.DispatcherServlet<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>servlet-class</span><span class="token punctuation">></span></span>
  	<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>async-supported</span><span class="token punctuation">></span></span>true<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>async-supported</span><span class="token punctuation">></span></span>
  	<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>load-on-startup</span><span class="token punctuation">></span></span>8<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>load-on-startup</span><span class="token punctuation">></span></span>
  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>servlet</span><span class="token punctuation">></span></span>
  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>servlet-mapping</span><span class="token punctuation">></span></span>
  	<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>servlet-name</span><span class="token punctuation">></span></span>dispatcher<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>servlet-name</span><span class="token punctuation">></span></span>
  	<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>url-pattern</span><span class="token punctuation">></span></span>/<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>url-pattern</span><span class="token punctuation">></span></span>
  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>servlet-mapping</span><span class="token punctuation">></span></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><strong>The End</strong></p>
<p>After re running the project, call the interface, and the idea console has no relevant prompt of <strong>dispatcherservlet</strong>, which is solved successfully.</p>
</div></template>
